services:
  - type: web
    name: moodtracker-api
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: http://localhost:4200,capacitor://localhost,ionic://localhost,https://moodtracker-api.onrender.com
